### ISSUE TITLE
이미지, 사운드파일 추가 요청

### ISSUE THREAD

**Issue by FantasticChoi** [FantasticChoi/shooting-game#8]
게임에 필요한 이미지 파일이나 사운드 파일 추가 요청바랍니다.

**Comment by FantasticChoi** [comment]
fighter2 이미지 추가 완료
![fighter2](https://user-images.githubusercontent.com/49021382/58609126-72fdd100-82e1-11e9-8593-26f945c7f936.png)

**Comment by depp9876** [comment]
효과음 추가 완료
att-sound1-9.ogg
beatt-sound4.ogg
weapon-sound1.ogg

**Comment by FantasticChoi** [comment]
bullet2 개체 이미지 추가
![bullet2](https://user-images.githubusercontent.com/49021382/58770493-418b4b00-85ea-11e9-9fc6-200ec14b89cd.png)

**Comment by FantasticChoi** [comment]
완료!
